### ISSUE TITLE
TODO for 0.0.3

### ISSUE THREAD

**Issue by Keats** [getzola/zola#5]
- [x] Fill prev/next on pages
- [ ] Pagination (#7)
- [ ] Prettier command line output
- [ ] Choose a different config file (#8)
- [x] Choose code highlighting theme
- [ ] Put it on AUR (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ripgrep for ripgrep for example)
